name: "query_bls"
backend: "python"
max_batch_size: 0
input [
  {
    name: "INPUT_QUERY_TEXT"
    data_type: TYPE_STRING
    dims: [ 1 ]
  },
  {
    name: "INPUT_QUESTION_AUDIO_PATH"
    data_type: TYPE_STRING
    dims: [ 1 ]
  },
  {
    name: "INPUT_QUESTION_TRANSCRIPT_PATH"
    data_type: TYPE_STRING
    dims: [ 1 ]
  },
  {
    name: "INPUT_TOP_K"
    data_type: TYPE_UINT32
    dims: [ 1 ]
  }
]
output [
  {
    name: "OUTPUT_ANSWER"
    data_type: TYPE_STRING
    dims: [ 1 ]
  }
]
instance_group [
  {
    count: 1
    kind: KIND_CPU
  }
]
