name: "asr_whisper"
backend: "python"
max_batch_size: 0
input [
  {
    name: "INPUT_AUDIO_PATH"
    data_type: TYPE_STRING
    dims: [ 1 ]
  }
]
output [
  {
    name: "OUTPUT_TRANSCRIPT"
    data_type: TYPE_STRING
    dims: [ 1 ]
  }
]
instance_group [
  {
    count: 1
    kind: KIND_CPU
  }
]
